#!/usr/bin/env node
/**
 * Per-harness skill compiler (ADR-0005: single source, compiled per harness).
 *
 * Canonical source: skills/<name>/SKILL.md (used natively by Claude Code via
 * .claude-plugin/ and by Codex/any AGENTS.md-reading agent).
 * Generated here:
 *   - .cursor/rules/chitra.mdc            (Cursor project rule)
 *   - skills/manifest.json                (sha256 per skill — install integrity)
 *
 * Regenerate after any skill edit: node scripts/build-skills.mjs
 * CI-style check: node scripts/build-skills.mjs --check  (fails if outputs are stale)
 */
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");

const skillDirs = readdirSync(path.join(root, "skills"), { withFileTypes: true })
  .filter((d) => d.isDirectory() && existsSync(path.join(root, "skills", d.name, "SKILL.md")))
  .map((d) => d.name)
  .sort();

// ── manifest with content hashes ──────────────────────────────────────────
const manifest = {
  $comment: "Generated by scripts/build-skills.mjs — do not edit. Hashes verify skill integrity across install channels.",
  version: JSON.parse(readFileSync(path.join(root, "core/package.json"), "utf8")).version,
  skills: Object.fromEntries(
    skillDirs.map((name) => {
      const body = readFileSync(path.join(root, "skills", name, "SKILL.md"), "utf8");
      return [name, { sha256: createHash("sha256").update(body).digest("hex"), bytes: body.length }];
    })
  ),
};
const manifestJson = JSON.stringify(manifest, null, 2) + "\n";

// ── Cursor rule: a router that defers to the canonical SKILL.md files ─────
const frontmatterOf = (name) => {
  const src = readFileSync(path.join(root, "skills", name, "SKILL.md"), "utf8");
  const m = src.match(/^---\n([\s\S]*?)\n---/);
  const desc = m?.[1].match(/description:\s*(.+)/)?.[1] ?? "";
  return desc.trim();
};

const mdc = `---
description: Chitra — create or critique cinematic motion-design videos. Apply when the user asks for a video, launch film, promo, social clip, motion design, or a review of rendered video evidence.
alwaysApply: false
---

# Chitra (compiled rule — canonical source: skills/*/SKILL.md)

This repository creates cinematic videos through a directed, gated, critiqued pipeline. Do not improvise a workflow; follow the canonical skill documents:

${skillDirs.map((n) => `- **${n}** — ${frontmatterOf(n)}\n  → Follow \`skills/${n}/SKILL.md\` exactly.`).join("\n")}

Toolchain: \`node core/dist/cli/index.js <init|validate|check|frame|render|evidence|clean|probe>\` (build once: \`cd core && npm install && npx tsc\`; requires ffmpeg). The motion law is \`docs/motion/motion-language.md\` — cite rules by ID, never restate values. IR reference: \`core/src/ir/schema.ts\`. Never present a render whose \`chitra check\` is not green.
`;

const outputs = [
  [path.join(root, "skills/manifest.json"), manifestJson],
  [path.join(root, ".cursor/rules/chitra.mdc"), mdc],
];

let stale = 0;
for (const [file, content] of outputs) {
  const current = existsSync(file) ? readFileSync(file, "utf8") : null;
  if (current === content) continue;
  stale++;
  if (check) {
    console.error(`✖ stale: ${path.relative(root, file)} — run: node scripts/build-skills.mjs`);
  } else {
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileSync(file, content);
    console.log(`✔ wrote ${path.relative(root, file)}`);
  }
}
if (check && stale) process.exit(1);
if (!stale) console.log("✔ all compiled skill artifacts up to date");
